### ISSUE TITLE
Invalid package "A local file header is corrupt" when push package

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/SignService#60] opened 2018-12-04 20:11 UTC
Signing this package makes it fail to be pushed (or opened via Nuget package explorer), with the following error:
`The nuget command failed with exit code(1) and error(Response status code does not indicate success: 400 (A local file header is corrupt.).)`

[Uno.SourceGenerationTasks.1.29.0-dev.nuget-sign.189.nupkg.zip](https://github.com/onovotny/SignService/files/2645940/Uno.SourceGenerationTasks.1.29.0-dev.nuget-sign.189.nupkg.zip)

**Comment by onovotny** [comment] 2018-12-04 20:19
Thanks. What, if any, filter did you use on it?

**Comment by jeromelaban** [comment] 2018-12-04 20:42
I'm using this for now:
```
build\host\net461\Uno.SourceGeneration.dll
build\host\net461\Uno.SourceGeneration.Host.exe
build\host\netcoreapp2.1\Uno.SourceGeneration.dll
build\host\netcoreapp2.1\Uno.SourceGeneration.Host.dll
build\Dev15.0\Uno.SampleGenerators.dll
build\Dev15.0\Uno.SourceGeneration.dll
```

There's one more file that should be, but the filename is generated so I'll add it to the list later on.

**Comment by onovotny** [comment] 2018-12-04 20:44
Is that the filter that works, or the case that failed?

BTW, the filter supports globs like `**\Uno.*`

**Comment by jeromelaban** [comment] 2018-12-04 20:46
Ah! Good to know, I'll use the globbing then. It's the filters that work.

**Comment by Aaronontheweb** [comment] 2019-05-03 01:02
I'm having this issue too - signing a .NET Core global tool using a cert that I've used for a number of other packages.

Build steps: https://github.com/petabridge/petabridge-dotnet-new/blob/dev/src/Content/Petabridge.Library/build-system/windows-release.yaml

https://github.com/petabridge/petabridge-dotnet-new/blob/8d78d43e690534e5412df0f3686247c590630ad9/src/Content/Petabridge.Library/build.fsx#L133-L179

We're signing the NuGet packages themselves.

**Comment by onovotny** [comment] 2019-05-03 01:03
Does this repro if you use a test cert with the nuget.exe sign command?

**Comment by Aaronontheweb** [comment] 2019-05-03 16:19
@onovotny haven't tried that yet - I'll look into doing that ASAP

**Comment by Aaronontheweb** [comment] 2019-05-03 16:37
Added the signed NuGet packages here: https://github.com/petabridge/Incrementalist/releases/tag/0.1.0

If you want to create an unsigned copy of these packages locally - clone the repository and run `./build.cmd nuget` - they'll be sitting in the `bin\nuget` folder.

**Comment by Aaronontheweb** [comment] 2019-05-03 21:04
So if I use `nuget sign` using the same certificate on my local machine, without going through SignService then I'm able to avoid this issue. Certificate appears to work fine.

**Comment by onovotny** [comment] 2019-05-03 21:27
How about with the latest sign service?

**Comment by Aaronontheweb** [comment] 2019-05-07 22:58
Just tried with the latest SignService... Still getting this error even with that. Verification fails on both v4.9.4 and v5.0.0 versions of NuGet

**Comment by Aaronontheweb** [comment] 2019-05-07 23:45
Ok, so I found an important distinction here - the error only occurs for my .NET Core global tool packages. Not traditional DLLs.

**Comment by Aaronontheweb** [comment] 2019-05-08 01:32
Filed an issue with NuGet here too: https://github.com/NuGet/Home/issues/8111

**Comment by glennawatson** [comment] 2019-05-25 08:51
I am starting to get this issue with one of the RxUI 

It appears if the .nuspec file inside the NuGet package is getting corrupted. If I use the windows explorer zip functionality it can't read the .nuspec file in the root folder.  I can open a read other files.

I am using a filter in the csproj file 

```xml
<Project Sdk="MSBuild.Sdk.Extras">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net461</TargetFrameworks>
    <PackageId>Pharmacist.MSBuildTask</PackageId>
    <!-- forces SDK to copy dependencies into build output to make packing easier -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);PackBuildOutputs</TargetsForTfmSpecificContentInPackage>
    <NoWarn>$(NoWarn);CA1819</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Condition="'$(TargetFramework)' == 'net461' " Include="Microsoft.Build.Tasks.Core" Version="14.3" PrivateAssets="all" />
    <PackageReference Condition="'$(TargetFramework)' == 'netstandard2.0' " Include="Microsoft.Build.Tasks.Core" Version="15.1.548" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup Label="Package">
    <None Include="targets\Pharmacist.MSBuildTask.targets" PackagePath="build\net461" Pack="true" />
    <None Include="targets\Pharmacist.MSBuildTask.targets" PackagePath="buildTransitive\net461" Pack="true" />
    <None Include="targets\Pharmacist.MSBuildTask.targets" PackagePath="build\netstandard2.0" Pack="true" />
    <None Include="targets\Pharmacist.MSBuildTask.targets" PackagePath="buildTransitive\netstandard2.0" Pack="true" />
  </ItemGroup>

  <Target Name="PackBuildOutputs">
    <ItemGroup>
      <TfmSpecificPackageFile Include="bin\$(Configuration)\$(TargetFramework)\**\*" PackagePath="build\$(TargetFramework)\%(RecursiveDir)" />
    </ItemGroup>
  </Target>

  <ItemGroup>
    <ProjectReference Include="..\Pharmacist.Core\Pharmacist.Core.csproj" PrivateAssets="All" />
  </ItemGroup>
</Project>
```

**Comment by onovotny** [comment] 2019-05-25 08:53
This is starting to sound like a potential issue with the ZipArchive functionality somewhere, but we need a consistent repro for them to debug.

**Comment by glennawatson** [comment] 2019-05-25 09:00
Well I have a 100% reproducable use case here https://github.com/reactiveui/Pharmacist/tree/a0d449845d1d6eacb7415726d12a4bf697f353c9

One other thing is because it's a NuGet task I have to include a bunch of assemblies, so the zip is getting pretty large.

**Comment by onovotny** [comment] 2019-05-25 09:04
The size of the zip shouldn't be an issue; the pipe from Pipelines to App Services is very fast.

When I look at the artifacts here, I see four: which is the one failing?

https://dev.azure.com/dotnet/ReactiveUI/_build/results?buildId=17672&view=results

**Comment by glennawatson** [comment] 2019-05-25 09:06
Pharmacist.MsBuildTask.nupg

**Comment by glennawatson** [comment] 2019-05-25 09:39
The file still works with a regular "nuget sign" with a testing signature just in case you haven't had time to test yet.

**Comment by onovotny** [comment] 2019-05-30 18:54
I just took the unsigned one from the build and tried it against my local dev instance, and it signed without any errors.

**Comment by glennawatson** [comment] 2019-05-30 23:17
Ah so might be just a waiting game while we get the runtime to update

**Comment by onovotny** [comment] 2019-10-06 22:50
Closing due to age. Please re-open this occurs again with the latest client.

**Closed by onovotny** 2019-10-06 22:50 UTC
Labels: bug
